filter:
    excluded_paths:
        - 'tests/*'
        - 'example/'
        - 'review/'
build:
    tests:
        override:
            - command: 'mkdir -p build/logs'
            - command: 'php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
              coverage:
                  file: 'build/logs/clover.xml'
                  format: 'clover'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - command: phpcs-run ./
                      use_website_config: false
                    - php-scrutinizer-run
tools:
    php_cs_fixer:
        config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                bitwise: true
                unary_additive: true
                concatenation: true
